# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bellmanFordRcpp <- function(adjacencyMatrix, source) {
    .Call(`_AlgorithmicDijkstra_bellmanFordRcpp`, adjacencyMatrix, source)
}

DijkstraC <- function(adjacency_matrix, source) {
    .Call(`_AlgorithmicDijkstra_DijkstraC`, adjacency_matrix, source)
}

dijkstraRcpp <- function(graph, source, dest) {
    invisible(.Call(`_AlgorithmicDijkstra_dijkstraRcpp`, graph, source, dest))
}

