# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bellman-Ford's Algorithm to find shortest path from a node to others
#'
#' @param matriceAdjacence Data.frame object with three variables (from, to and weight)
#' that contains the edges of the graph_DataFrame (from, to) with the weight of the edge (w)
#' @param source initial node (could be int or str).
#' @return list of two elements.
#' Distance: the shortest distance from the start node to other nodes (vector)
#' parents : the predecessor of each node (vector)
#' @export
#' @examples
#' matriceAdjacence = t(matrix(data = c(0  , 0  ,  0  ,  0  ,  0  ,    5  , 0,
#'                                    3  , 0  ,  0  ,  10 ,  3  ,   11  , 0,
#'                                    0  , 1  ,  0  ,  7  ,  0  ,   0   , 0,
#'                                    0  , 0  ,  0  ,  0  ,   0 ,    0  , 0,
#'                                    0  , 0  ,  0  ,  4  ,  0  ,    0  , 0,
#'                                    1  , 0  ,  0  ,  0  ,  0  ,    0  , 0,
#'                                    5  , 0  ,  0  ,  0  ,  4  ,    0  , 0), nrow  = 7))
#' bellmanFordRcpp(matriceAdjacence,2)
#'
bellmanFordRcpp <- function(matriceAdjacence, source) {
    .Call(`_AlgorithmicDijkstra_bellmanFordRcpp`, matriceAdjacence, source)
}

#' Dijkstra Algorithm to find shortest path from a node to others
#'
#' @param matriceAdjacence Data.frame object with three variables (from, to and weight)
#' that contains the edges of the graph_DataFrame (from, to) with the weight of the edge (w)
#' @param source initial node (could be int or str).
#' @return list of two elements.
#' Distance: the shortest distance from the start node to other nodes (vector)
#' parents : the predecessor of each node (vector)
#' @export
#' @examples
#' matriceAdjacence = t(matrix(data = c(0  , 0  ,  0  ,  0  ,  0  ,    5  , 0,
#'                                    3  , 0  ,  0  ,  10 ,  3  ,   11  , 0,
#'                                    0  , 1  ,  0  ,  7  ,  0  ,   0   , 0,
#'                                    0  , 0  ,  0  ,  0  ,   0 ,    0  , 0,
#'                                    0  , 0  ,  0  ,  4  ,  0  ,    0  , 0,
#'                                    1  , 0  ,  0  ,  0  ,  0  ,    0  , 0,
#'                                    5  , 0  ,  0  ,  0  ,  4  ,    0  , 0), nrow  = 7))
#' DijkstraC(matriceAdjacence,2)
#'
NULL

DijkstraC <- function(adjacency_matrix, source) {
    .Call(`_AlgorithmicDijkstra_DijkstraC`, adjacency_matrix, source)
}

#' Dijkstra Algorithm to find shortest path from a node to others
#'
#' @param matriceAdjacence Data.frame object with three variables (from, to and weight)
#' that contains the edges of the graph_DataFrame (from, to) with the weight of the edge (w)
#' @param source initial node (could be int or str).
#' @return list of two elements.
#' Distance: the shortest distance from the start node to other nodes (vector)
#' parents : the predecessor of each node (vector)
#' @export
#' @examples
#' matriceAdjacence = t(matrix(data = c(0  , 0  ,  0  ,  0  ,  0  ,    5  , 0,
#'                                    3  , 0  ,  0  ,  10 ,  3  ,   11  , 0,
#'                                    0  , 1  ,  0  ,  7  ,  0  ,   0   , 0,
#'                                    0  , 0  ,  0  ,  0  ,   0 ,    0  , 0,
#'                                    0  , 0  ,  0  ,  4  ,  0  ,    0  , 0,
#'                                    1  , 0  ,  0  ,  0  ,  0  ,    0  , 0,
#'                                    5  , 0  ,  0  ,  0  ,  4  ,    0  , 0), nrow  = 7))
#' dijkstraRcpp(matriceAdjacence,2, 5)
#'
NULL

dijkstraRcpp <- function(graph, source, dest) {
    invisible(.Call(`_AlgorithmicDijkstra_dijkstraRcpp`, graph, source, dest))
}

